# SAM configuration file for Enhanced Order Prediction Solution

version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "item-prediction"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=dev",
    "BedrockModelId=anthropic.claude-3-sonnet-20240229-v1:0",
    "EnableProductLevelForecasting=true"
]

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
fail_on_empty_changeset = false
resolve_s3 = true
stack_name = "item-prediction"
s3_prefix = "item-prediction"
region = "us-east-1"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" BedrockModelId=\"anthropic.claude-3-sonnet-20240229-v1:0\" SageMakerEndpointName=\"hybrent-deepar-2025-07-20-23-56-22-287\" EnableProductLevelForecasting=\"true\""
image_repositories = []

[default.package]
[default.package.parameters]
s3_prefix = "item-prediction"

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
